# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.basenube.com
title: Base Nube
email: your-email@domain.com
author: Ron Sweeney
description: > # "Write an awesome description for your new site here. 
  
copyright: 'Copyright &copy; 2018 baseNUBE. All Rights Reserved.'
credits: 'Credits: '

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/basenube
