# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Stacks', folder: 'pages', file: 'facts.html'}
- {name: 'Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Partners', folder: 'pages', file: 'documentation.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/ronsween'}
- {icon: 'envelope', link: 'mailto:ron.sweeney@integrationrequired.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'I like to be shared...'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
