site_name: baseNUBE Documentation Hub
theme: 
  name: material
  custom_dir: 'theme'
  extra:
  logo:
    icon: 'cloud'
  extra_css:
  - 'stylesheets/extra.css'
google_analytics: ['UA-119128826-1', 'basenube.com']
